// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          pgtype.UUID      `json:"id"`
	Name        pgtype.Text      `json:"name"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
	CompletedBy pgtype.Text      `json:"completed_by"`
}
